# Generated by Django 3.2.13 on 2022-07-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tremapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.TextField(verbose_name='Date e.g 20th, June 2022.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pst_title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
