# Generated by Django 3.1.1 on 2022-07-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tremapp', '0003_alter_post_pst_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srm_title', models.CharField(max_length=50, verbose_name='Sermon Title')),
                ('vid_link', models.TextField(verbose_name='Video Link')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
