# Generated by Django 3.1.1 on 2022-07-26 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tremapp', '0004_auto_20220726_0456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SermonPost',
        ),
        migrations.AddField(
            model_name='post',
            name='text_date',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Date e.g 20th, June 2022.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
